config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'games#index'
  get '/games', to: 'games#index'

  namespace :games do
    resources :rps, as: 'rps', except: [:edit,:destroy,:update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games/rps_controller.rb
class Games::RpsController < ApplicationController
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h1>Welcome to the Games Page</h1>

<ul>
  <li><%= link_to("Rock, Paper, Scissors", games_rps_index_path) %></li>
</ul>

app/views/games/rps/index.html.erb
<h1>Rock, Paper, Scissors</h1>

<div><%= link_to("New Game", new_games_rps_path) %>
<span>Since this is the index of the RPS game, we will probably want to list all of the games that the server has saved here</span>
<span>Each game in the list can then provide a link to the Show page where we can see how many rounds were played and what the current score is</span>
<span>This page can also provide a link to play a new game which will take you to the new rps path</span>

<div>
  <ul>
    <li><%= link_to("Game 1", games_rps_path(1)) %></li>
    <li><%= link_to("Game 2", games_rps_path(2)) %></li>
  </ul>
</div>

app/views/games/rps/new.html.erb
<h1>Rock, Paper, Scissors</h1>

<input type="button" val="Start Game" />
<span>This is the page that we would want to hook our javascript into</span>
<span>Use jQuery to add a handler to the click event of the Start Game button which can trigger the game to begin</span>


<% content_for(:footer) do %>
  <%= javascript_include_tag('games/rps.js') %>
<% end %>

app/views/games/rps/show.html.erb
<h1>Rock, Paper, Scissors</h1>
<span>Player 1 vs Player 2</span>
<span>Rounds: 10</span>
<span>Player 1 Score: 7</span>
<span>Player 2 Score: 3</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FantasticOctoDisco</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <%= content_for(:footer) if content_for?(:footer) %>
</html>